#ifndef ITEMASSISTANTCORE_GLOBAL_H
#define ITEMASSISTANTCORE_GLOBAL_H

#include <Qt/qglobal.h>

#ifdef ITEMASSISTANTCORE_LIB
# define ITEMASSISTANTCORE_EXPORT Q_DECL_EXPORT
#else
# define ITEMASSISTANTCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // ITEMASSISTANTCORE_GLOBAL_H
